when:
  branch: main
  event: push

steps:
  prettier:
    image: woodpeckerci/plugin-prettier:next
    settings:
      check: false

  run-pre-commit-hooks:
    image: codeberg.org/sp1thas/woodpecker-ci-pre-commit-runner
    settings:
      args: "--all-files"
