when:
  event:
    - pull_request
    - pull_request_metadata
  branch: main

skip_clone: true

steps:
  env:
    image: busybox
    volumes:
      - ${PWD }/config:/etc/configs
    commands:
      - env
      - ls -l /etc/configs
