when:
  event:
    - pull_request
    - pull_request_metadata
  branch: main

steps:
  env:
    image: busybox
    volumes:
      - /c/Users/Ariel/vscodeProjects/playground/cookielevanna5/computer-networks/config:/etc/config
    commands:
      - env
      - ls -l /etc/config
