when:
  event:
    - pull_request
    - pull_request_metadata
  branch: main

steps:
  env:
    image: busybox
    volumes:
      - agent-config-woodpecker-agent-0:/etc/config
    commands:
      - env
      - ls -l /etc/config
